// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYiThdoV6oap6Mj5LG_Tum34u5jJAnLO0',
    appId: '1:255200518942:web:958be7b15014dd9e41df0f',
    messagingSenderId: '255200518942',
    projectId: 'fridgebuddyflutter',
    authDomain: 'fridgebuddyflutter.firebaseapp.com',
    storageBucket: 'fridgebuddyflutter.firebasestorage.app',
    measurementId: 'G-N8KMG5JKG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0crdr8Cz9DGBDCZfxUbnumF0QSMZzMjU',
    appId: '1:255200518942:android:46e2faa4bb00655541df0f',
    messagingSenderId: '255200518942',
    projectId: 'fridgebuddyflutter',
    storageBucket: 'fridgebuddyflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdK1W8w_xW7VPC1tBvIITc2UbI21Qr0zM',
    appId: '1:255200518942:ios:a64007a8fef5862b41df0f',
    messagingSenderId: '255200518942',
    projectId: 'fridgebuddyflutter',
    storageBucket: 'fridgebuddyflutter.firebasestorage.app',
    iosBundleId: 'com.example.fridgebuddyflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdK1W8w_xW7VPC1tBvIITc2UbI21Qr0zM',
    appId: '1:255200518942:ios:a64007a8fef5862b41df0f',
    messagingSenderId: '255200518942',
    projectId: 'fridgebuddyflutter',
    storageBucket: 'fridgebuddyflutter.firebasestorage.app',
    iosBundleId: 'com.example.fridgebuddyflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYiThdoV6oap6Mj5LG_Tum34u5jJAnLO0',
    appId: '1:255200518942:web:ac3f5dbdcf8086bc41df0f',
    messagingSenderId: '255200518942',
    projectId: 'fridgebuddyflutter',
    authDomain: 'fridgebuddyflutter.firebaseapp.com',
    storageBucket: 'fridgebuddyflutter.firebasestorage.app',
    measurementId: 'G-J1TEWMZYLB',
  );
}
